import type { NextPage, GetStaticProps, GetStaticPaths, GetServerSideProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import axios from 'axios'


interface ProductDetails{
  name: string,
  slug: string
}

interface iProps{
  products: ProductDetails[]
}




const Home: NextPage<iProps> = ({products}: iProps) => {
  console.log(products)
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        Oroton Front End Prototype
        </h1>
        <div className={styles.grid}>
        {products.map((product) => <a href={`/products/${product.slug}`} className={styles.card}>
            <h2>{product.name} &rarr;</h2>
          </a>)}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

async function getProductNamesSlugs(){
  const res = await axios({
    url: 'https://ap-southeast-2.aws.realm.mongodb.com/api/client/v2.0/app/application-0-lmrek/graphql',
    method: 'post',
    headers:{
      'apiKey': `jbLQSDbjFLPNpsd05dDug5syEQk4ZC7Hq1Les4PnxoiDNka3FGLdLb4ECvBGAipd`
  },
  data:{
    query: `
    query {
      products{
        name
        slug
        
      }
    }
    `
  }
  })
  return res
}

async function getProductSlugs(){
  const res = await axios({
    url: 'https://ap-southeast-2.aws.realm.mongodb.com/api/client/v2.0/app/application-0-lmrek/graphql',
    method: 'post',
    headers:{
      'apiKey': `jbLQSDbjFLPNpsd05dDug5syEQk4ZC7Hq1Les4PnxoiDNka3FGLdLb4ECvBGAipd`
  },
  data:{
    query: `
    query {
      products{
        slug
      }
      }
    `
  }
  })
  return res
}


export const getStaticProps: GetStaticProps = async (context) => {
  const slugs = await getProductSlugs()
  console.log(slugs.data.data.products)
  const {data} = await getProductNamesSlugs()
  const productDetailsArr : ProductDetails[] = data.data.products

  return {
    props:{
      products: productDetailsArr,
    }
  }
}

export default Home
